<%@ Page Title="" Language="C#" MasterPageFile="~/SMS.master" UnobtrusiveValidationMode="none" AutoEventWireup="true" CodeFile="Adminpage.aspx.cs" Inherits="Adminpage" %>

<asp:Content ID="Content1" ContentPlaceHolderID="ContentPlaceHolder1" Runat="Server">
    <h1 style="border: medium double darksalmon; font-family: 'Arial Rounded MT Bold'; font-size: xx-large; font-weight: bolder; color: darksalmon; text-transform: capitalize;">THIS IS THE ADMIN PAGE ...</h1>
    <br />
    
    <asp:DropDownList ID="DropDownList1" runat="server" BackColor="White" Font-Bold="True" Font-Names="Arial Rounded MT Bold" Font-Size="Larger" ForeColor="DarkSeaGreen">
        <asp:ListItem>course</asp:ListItem>
        <asp:ListItem>Student</asp:ListItem>
        <asp:ListItem>teacher</asp:ListItem>

    </asp:DropDownList>
    <asp:Button ID="ButSubmit" runat="server" Text="Submit" OnClick="ButSubmit_Click" BackColor="White" BorderColor="DarkSalmon" BorderStyle="Solid" BorderWidth="2px" Font-Bold="True" Font-Names="Arial Rounded MT Bold" Font-Size="Large" ForeColor="DarkSeaGreen" ToolTip="click to view data" />

    <asp:GridView ID="Gdcourse" runat="server" DataKeyNames="Cid" AutoGenerateEditButton="true" AutoGenerateDeleteButton="true" OnRowCancelingEdit="Gdcourse_RowCancelingEdit" OnRowDeleting="Gdcourse_RowDeleting" OnRowEditing="Gdcourse_RowEditing" OnRowUpdating="Gdcourse_RowUpdating"></asp:GridView>
     <asp:GridView ID="Gdstudent" runat="server" DataKeyNames="Stid" AutoGenerateEditButton="true" AutoGenerateDeleteButton="true" OnRowCancelingEdit="Gdstudent_RowCancelingEdit" OnRowDeleting="Gdstudent_RowDeleting" OnRowEditing="Gdstudent_RowEditing" OnRowUpdating="Gdstudent_RowUpdating"></asp:GridView>
     <asp:GridView ID="Gdteacher" runat="server" DataKeyNames="Tid" AutoGenerateEditButton="true" AutoGenerateDeleteButton="true" OnRowCancelingEdit="Gdteacher_RowCancelingEdit" OnRowDeleting="Gdteacher_RowDeleting" OnRowEditing="Gdteacher_RowEditing" OnRowUpdating="Gdteacher_RowUpdating"></asp:GridView>
</asp:Content>

